<a href="https://colab.research.google.com/github/Polyakova-Dina/Numpy_solutions/blob/main/Numpy_solutions111.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hi')


hi


In [ ]:
#a. Импортируйте библиотеку NumPy
import numpy as np

In [4]:
#b. Создайте массив из 10 нулей
import numpy as np
array=np.zeros(10)
print("Массив из 10 нулей:")
print(array)


Массив из 10 нулей:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#c. Создать массив из 10 единиц
import numpy as np
array1=np.ones(10)
print("Массив из 10 единиц:")
print(array1)

Массив из 10 единиц:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#d. Создать массив из 10 пятерок
array=np.ones(10)*5
print("Массив из 10 пятерок::")
print(array)

Массив из 10 пятерок::
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#e. Создать массив из целых чисел от 10 до 50
arr = np.arange(10, 50, 1)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#f. Создать массив из четных чисел от 10 до 50
arr = np.arange(10, 50, 2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
#g. Создать матрицу 3х3 с числами от 0 до 8
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#h. Создать единичную матрицу 3x3
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#i. Используйте NumPy для генерации случайного числа от 0 до 1
rand_num = np.random.normal(0,1,1)
print("Случайное число от 0 до 1:")
print(rand_num)

Случайное число от 0 до 1:
[-0.03478508]


In [ ]:
#j. Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
rand_num = np.random.normal(0,1,25)
print(rand_num)

[ 0.57512305  0.80136056  0.7061575   0.09392284 -1.05061701  1.13854098
  0.81448425 -1.24718178  0.8639451   0.35407527 -0.66836849 -0.38086861
  1.36675551 -1.36330485  0.46497815 -0.68120819  0.98278724  1.61657069
 -0.2532506   0.89433374 -0.51012569  0.44666949 -0.27136486  0.22053434
 -0.85803339]


In [ ]:
#k. Создайте следующую матрицу используя функции библиотеки NumPy
a=np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(a)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
#l. Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Эта матрица будет использоваться в последующих задачах
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#Необходимо написать код который вернет следующую матрицу из стартовой:
b = mat[2:, 1:]
print(b)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
#m. Написать код обращения к элементу который вернет значение 20 из стартовой матрицы задачи l
c = mat[3, 4]
print(c)

20


In [ ]:
#n. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
d = mat[1:4,1:2]
print(d)

[[ 7]
 [12]
 [17]]


In [ ]:
#o. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
d = mat[4:5,:]
print(d)

[[21 22 23 24 25]]


In [ ]:
#p. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
d = mat[3:5,:]
print(d)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#q. Получить сумму всех значений в стартовой матрице mat
d=np.sum(mat)
print(d)

325


In [ ]:
#r. Получить стандартное отклонение в стартовой матрице mat
d=np.std(mat)
print(d)

7.211102550927978


In [ ]:
#s. Получить сумму значений в колонках в стартовой матрице mat
sumR = mat.sum(axis=0)
print(sumR)

[55 60 65 70 75]
